language: cpp

compiler:
 - clang
 - gcc

before_install:
  - sudo pip install cpp-coveralls

install:
  - if [ "$CXX" == "g++"]; then .travis_scripts/gcc.sh; fi

script:
 - ./configure && make && make check

