language: cpp

compiler: 
- gcc
- clang

env: 
  global: 
  - BOOST_VERSION_MIN="1.59.0"
  - BOOST_VERSION_MAX="1.60.0" # List of required boost libraries to build"
  - BOOST_LIBS="regex,system,test"
  - secure: c7M47d76dYyjOsYiRWdJ7DaKyV6qo9tUk1l+QlSTX5AgfWGGIsI3eWxHrSid/b1PXTVCOQTBwJKlM13gNPO5kLEAxrT/Bl8rtFUQdBwqA5gZaY1Yyt7h51hRR9GADwUY4lmudLBiPRDp8Pd3WSiP+gOud7hA8U/AP0BPBfbhDkhvUC6GqvHzEp28NIHB0nhOv4r4yl7C2UeNk358ipDmYqs89m17TNTmbReYjqiaswYSkhCjikUT33QyDTLwl502NBRIJZpZZZ3imxorSM4A1uQmuq5Ggx4PyODgt8MpzH/bCHeamNFzYCi/JSh+MsuOv6tD6xsM9p1MzI5Fg7eQk+FtdmfQhgyTYjg24Ugyn0rrnu2i26FjLqkX3jqdgIldncoerJZly92+M0wRv4IrjjQLCrNLT2Wv4WRElKR5W2dRSnKBT/vIrfJQU9HwYPvISLS3yhpm9NcZnP09Mfoe3xU1mrWnSfbsbXAQ6tfQ14ysOD2/8RhxG3+0lLqS5s5DWefqtz1ouXviLKPcO08kdlcKgTkbh8nZPJNm8byh01tJe0DRPY7z6TJJRMdE/+Yz9VsKjxs9KautacdJmYruVL6AlHb97FlzhvQhaCU5LpOkw2wO5AHpFfgvaygWvi9RQksrr4AulnAcIE7aikcXJnpEqzgup3AyNzlVFu/s1Fo=

before_install: 
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install valgrind python-yaml libyaml-dev build-essential libssh2-1-dev libarchive-dev clang
- sudo apt-get install gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
- sudo update-alternatives --config gcc
- sudo update-alternatives --config g++
- if [ "${TRAVIS_BRANCH}" = "master" ]; then export BOOST_VERSION="${BOOST_VERSION_MIN}"; else export BOOST_VERSION="${BOOST_VERSION_MAX}"; fi
- if [ -n "${BOOST_VERSION}" ]; then export BOOST_ROOT="${TRAVIS_BUILD_DIR}/../boost-trunk"; export CMAKE_MODULE_PATH="${BOOST_ROOT}"; fi
- if [ "${CXX}" = "g++" ]; then export CXX="$(which g++-4.8)"; export CC="$(which gcc-4.8)"; fi
- "if [ \"${TRAVIS_OS_NAME}\" = \"osx\" ]; then export DYLD_LIBRARY_PATH=\"${BOOST_ROOT}/lib\"; fi # c++ is a symlink to clang++, but the compiler behaves differently when invoked as c++"
- if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export CXX="$(which c++)"; export CC="$(which cc)"; fi
- .travis.scripts/travis-before-install.sh

install: 
- .travis.scripts/travis-install.sh

script: 
- ./configure --with-boost=${BOOST_ROOT} && make

after_success: 
- .travis.scripts/coveralls.sh

branches: 
  only: 
  - master
